### ISSUE TITLE
[question] is this deployed anywhere?

### ISSUE THREAD

**Issue by benjaminpjones** [govariants/client#3]
Just curious!  We are working on a similar project! (https://www.github.com/benjaminpjones/govariants)

**Comment by m09** [comment]
Amazing! Sadly no this is not deployed, we did not finish at the time. We still discuss it from time to time so we might come back to it at some point. I'll check out your work, that's great :)

**Comment by benjaminpjones** [comment]
Ah bummer, hope yall get a chance to work on it again! And thanks for the response 😀
